### ISSUE TITLE
Project stage 3 checklist

### ISSUE THREAD

**Issue by JakubRamisz** [stepniaczky/CP#7]
- [x] **Starting point**
  - [x] all UT are green
  - [x] the program behaves as expected (intermediate approval test)
- [x] **Data Layer**
  - [x] responsibility of this layer is
    - [x] to represent boundaries of the movement rectangle if necessary
    - [x] implement balls behavior as self-contained independent entities
    - [x] save diagnostic data to a file
  - [x] protect balls velocity against any influence from other balls and the environment behavior
  - [x] balls implementation uses parallel programming if applicable (depends on the run time platform)
  - [x] prove that the diagnostic logging doesn't have impact on the balls behavior
- [x] **Logic Layer**
  - [x] responsibility of this layer is to manage movement rectangle boundaries and balls interaction (collisions)
  - [x] prove that the protection of data (balls position on abstract table during collisions detection) integration is implemented
  - [x] `Logic` uses only the abstract `Data` layer API
- [x] **Presentation Layer (mvvm)**
  - [x] responsibility of this layer is to manage the graphical user interface (GUI)
  - [x] user => GUI interoperability must be implemented using interactive programming only
  - [x] GUI => the user interoperability must be implemented using reactive programming only (timer is not allowed)
  - [x] interoperability of the GUI and underlying layers must be synchronized
  - [x] prove that the protection of data (balls position on the screen) integration is implemented
- [x] **Testing**
  - [x] Unit Test - layers are tested independently using dependency injection (additional framework is not required)
  - [ ] Mock may be used for testing purpose (expected but not required)
